### PR TITLE
PR1: cleaning

### PR DESCRIPTION
**Pull request by bam241**
This also move SortsBid from enrich_function.cc to behavior_functions.h as it is needed for RandomEnrich

### CODE REVIEW

**Comment by gonuke** [comment]
The comments say that `SortBids` was moved from `enrich_functions` but I don't see `enrich_functions` in this PR?

**Comment by bam241** [comment]
yes!
it is because I first completely removed `enrich_functions` and then re-add it...

**Comment by bam241** [comment]
@gonuke fixed!

**Comment by gonuke** [comment]
Thanks @bam241

**Pull request merged**
