### PR TITLE
Cascade enrich

### PR DESCRIPTION
**Pull request by bam241**
This aims to fix the CascadeEnrich facility as well as the enrich_function:
in enrich_function:
- added a function to compute the cut value for the first ideal stage (enrich stage 0)
- build an ideal cascade from the feed/product/tail assay requirement: 
1- alpha is fixed across the different stages (so as deltaU), 
2- cut is recalculated to ensure alpha=beta 
- the flow per stage is then recalculated from the stage's cuts
- added a function to compute the assay of the different flows when the feed assay is the one use for the design: 
1- compute the assays as if the cascade is ideal
2- recalculate the stg_feed_assay as mix of the product of previous stage and tail of next stage (non idea symmetric cascade)
3- redo step 2 until sum of the differences between assays (with previous calculation) is < precision (default 1e-16)
- reshaped the `DesignCascade` function: now design the cascade Flow from the `max_feed_flow` variable, and then calculate if the number centrifuges required is exceed the `max_centrifuges` requirement, if so it scale down the `max_feed_flow` to match the `max_centrifuges` limit

to do this I also set-up 3 `struct`s `centrifuge_config`, `stg_config`, `cascade_config` allowing to simplify the exchange of the different information accros the methods....
-> next improvement is to move from structure to class, and have those method as class methods

in CascadeEnrich:
- removed SWU constrain
- split the feed_flow constrain and the feed_max_inventory
- design the cascade from the requirement
- bid/request now use properly the designed cascade, if the inventory assay does not match the design_feed_assay then the response of the CascadeEnrich is adapted...

### CODE REVIEW

**Comment by bam241** [comment]
@gonuke @mbmcgarry @nuclearkatie 
I finished my rework of the enrich_function.

the enrich methods are now split into 3 classes, CentrifugesConfig, StageConfig, and CascadeConfig.
I think this will allow a easier understanding of the different algorithms, and also allows further modifications if required...

**Comment by gonuke** [comment]
I wonder if we need to write a theory guide to support this code.  Given how often we have to revisit the fundamental equations, I am not sure I am confident reviewing it without a good document that describes what it should be doing, in theory.

**Comment by bam241** [comment]
@gonuke I agree

Maybe I can work on an application, write an article about this illustrated with the application, and use it as a reference for the theory ? And move everything forward together (review this PR in the same time as the article)

**Comment by gonuke** [comment]
I think we can write the theory part, in anticipation of it becoming a paper, before we have the application... and use the theory part to support the PR

**Comment by bam241** [comment]
new commits about:
- default constructor
- add new method to compute the response to non ideal feed assay (alpha = beta = const)
- increase number of centrifuge parameters modifiable by the user
- add some doc about the different variables
- fix calculation of the feed required when feed with non ideal assay feed

**Comment by bam241** [comment]
A draft of theory documentation is available there: https://github.com/bam241/publications/tree/cvt_cascadeenrich/paper

**Pull request closed without merging**
